### ISSUE TITLE
forms not working

### ISSUE THREAD

**Issue by bardolf69** [greys-bots/form-fox#12] opened 2021-10-18 12:56 UTC
ok I've got the bot all setup and can create forms etc. without a problem but when I post the form and try to use it's interaction to fill out the form nothing happens.

**Comment by selenated** [comment] 2021-10-18 14:17
hiya, can you make sure you have DMs turned on in the server? alternatively you can try DMing the bot first and then trying again

the bot needs to be able to DM you to go through the form, so that's usually where the issue is

**Comment by selenated** [comment] 2021-10-21 13:25
hi! been a few days- did you get things working?

**Comment by bardolf69** [comment] 2021-10-21 14:37
yeah sorry found the issue, as you suggested it was people blocking DMs from non-friends

**Comment by selenated** [comment] 2021-10-21 14:38
gotcha! i'll go ahead and close this up then

**Closed as completed by selenated** 2021-10-21 14:38 UTC
Labels: support
